# target                 border  bg        text      indicator  child_border
client.focused           $mauve  $mauve    $crust    $rosewater $mauve
client.focused_inactive  $mauve  $surface0 $text     $mauve     $mauve
client.unfocused         $overlay0 $base   $subtext1 $overlay0  $overlay0
client.urgent            $peach  $base     $peach    $overlay0  $peach
client.placeholder       $overlay0 $base   $text     $overlay0  $overlay0
client.background        $base

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:JetBrainsMono Nerd Font 11

# bar
bar {
  font pango:JetBrainsMono Nerd Font 11
  tray_output primary
  colors {
    background         $base
    statusline         $text
    focused_statusline $text
    focused_separator  $base

    # target           border bg        text
    focused_workspace  $base  $mauve    $crust
    active_workspace   $base  $surface2 $text
    inactive_workspace $base  $base     $text
    urgent_workspace   $base  $red      $crust
  }
}

# Hide window title bar
default_border pixel 2
default_floating_border pixel 2
for_window [class="^.*"] border pixel 2

#hide_edge_borders smart
gaps inner 6
gaps outer 3
