# target                 border   bg        text      indicator  child_border
client.focused           $base    $mauve    $crust    $lavender  $lavender
client.focused_inactive  $base    $surface1 $text     $base      $base
client.unfocused         $base    $base     $subtext1 $base      $base
client.urgent            $peach   $base     $peach    $overlay0  $peach
client.placeholder       $overlay0 $base    $text     $base      $overlay0
client.background        $base

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:JetBrainsMono Nerd Font 11

# bar
bar {
  font pango:JetBrainsMono Nerd Font 11
  tray_output primary
  colors {
    background         $base
    statusline         $text
    focused_statusline $text
    focused_separator  $base

    # target           border bg        text
    focused_workspace  $base  $mauve    $crust
    active_workspace   $base  $surface1 $text
    inactive_workspace $base  $base     $text
    urgent_workspace   $base  $red      $crust
  }
}

# Hide window title bar
default_border normal 2
default_floating_border normal 2
for_window [class="^.*"] border pixel 2

#hide_edge_borders smart
smart_borders on
gaps inner 6
gaps outer 3
