# target                 border    bg         text      indicator  child_border
client.focused           $mauve    $mauve     $mauve    $base      $lavender
client.focused_inactive  $blue     $blue      $blue     $base      $base
client.unfocused         $base     $surface2  $surface2 $base      $base
client.urgent            $peach    $base      $base     $overlay0  $peach
client.placeholder       $overlay0 $base      $base     $base      $overlay0
client.background        $base

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
# If color of the text is the same as the background and then font size 
# controls the thickness of the lines above.
font pango:JetBrainsMono Nerd Font 0

# Built-in i3bar with catppuccin colors.
# Can be enabled if polybar is not what you want.
#bar {
#  font pango:JetBrainsMono Nerd Font 11
#  tray_output primary
#  colors {
#    background         $base
#    statusline         $text
#    focused_statusline $text
#    focused_separator  $base
#
#    # target           border     bg        text
#    focused_workspace  $mauve     $mauve    $crust
#    active_workspace   $surface1  $surface2 $text
#    inactive_workspace $base      $base     $text
#    urgent_workspace   $base      $red      $crust
#  }
#}

# Hide window title bar
default_border pixel 2
default_floating_border pixel 2
for_window [class="^.*"] border pixel 2

hide_edge_borders smart
smart_borders on
gaps inner 6
gaps outer 4
