term xterm-kitty
enable_audio_bell no
confirm_os_window_close 0
copy_on_select yes
clipboard_control write-clipboard write-primary 

# this one will allow changing kitty theme from i3    
allow_remote_control yes
listen_on unix:/tmp/kitty-$USER

include ~/.config/kitty/themes/current.conf

# fonts
font_family   JetBrainsMono Nerd Font 


#remove padding around the window
window_padding_width 0

placement_strategy top-left
