# Override volume keys to use dunst-themed OSD.
bindsym XF86AudioRaiseVolume exec --no-startup-id ~/.config/i3/scripts/volume-osd.sh up
bindsym XF86AudioLowerVolume exec --no-startup-id ~/.config/i3/scripts/volume-osd.sh down
bindsym XF86AudioMute exec --no-startup-id ~/.config/i3/scripts/volume-osd.sh mute
