# GlobalProtect UI floating configuration for i3 window manager
# As it has a strange behavior that it dissapears and is not resizable
for_window [class="PanGPUI"] floating enable
for_window [class="PanGPUI"] move position center
